services:
  - type: web
    name: electricity-board-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: your-secret-key
